stages:
  - verify
  - build
  - publish

variables:
  DOCKER_BUILDKIT: "1"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_DEPTH: "1"

default:
  image: docker:28.1.1-git
  services:
    - name: docker:28.1.1-dind
  before_script:
    - docker version
    - docker buildx create --name gitlab-builder --use || docker buildx use gitlab-builder

verify:
  stage: verify
  script:
    - make lint-golangci-lint
    - make unit-tests

build:kms-server:
  stage: build
  script:
    - make local-kms-server-linux-amd64 DEST=_out
  artifacts:
    name: "kms-server-${CI_COMMIT_SHA}"
    expire_in: 1 week
    paths:
      - _out/kms-server-linux-amd64

