// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: kms/kms.proto

package kms

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node UUID as string. Heartbeat requests resolve node identity server-side and may leave it empty.
	NodeUuid string `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	// Data to encrypt or decrypt. Heartbeat does not use it.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_kms_kms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_kms_kms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_kms_kms_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is encrypted/decrypted response.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_kms_kms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_kms_kms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_kms_kms_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_kms_kms_proto protoreflect.FileDescriptor

const file_kms_kms_proto_rawDesc = "" +
	"\n" +
	"\rkms/kms.proto\x12\n" +
	"sidero.kms\":\n" +
	"\aRequest\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xac\x01\n" +
	"\n" +
	"KMSService\x126\n" +
	"\tHeartbeat\x12\x13.sidero.kms.Request\x1a\x14.sidero.kms.Response\x121\n" +
	"\x04Seal\x12\x13.sidero.kms.Request\x1a\x14.sidero.kms.Response\x123\n" +
	"\x06Unseal\x12\x13.sidero.kms.Request\x1a\x14.sidero.kms.ResponseB#Z!github.com/siderolabs/kms/api/kmsb\x06proto3"

var (
	file_kms_kms_proto_rawDescOnce sync.Once
	file_kms_kms_proto_rawDescData []byte
)

func file_kms_kms_proto_rawDescGZIP() []byte {
	file_kms_kms_proto_rawDescOnce.Do(func() {
		file_kms_kms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_kms_proto_rawDesc), len(file_kms_kms_proto_rawDesc)))
	})
	return file_kms_kms_proto_rawDescData
}

var file_kms_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kms_kms_proto_goTypes = []any{
	(*Request)(nil),  // 0: sidero.kms.Request
	(*Response)(nil), // 1: sidero.kms.Response
}
var file_kms_kms_proto_depIdxs = []int32{
	0, // 0: sidero.kms.KMSService.Heartbeat:input_type -> sidero.kms.Request
	0, // 1: sidero.kms.KMSService.Seal:input_type -> sidero.kms.Request
	0, // 2: sidero.kms.KMSService.Unseal:input_type -> sidero.kms.Request
	1, // 3: sidero.kms.KMSService.Heartbeat:output_type -> sidero.kms.Response
	1, // 4: sidero.kms.KMSService.Seal:output_type -> sidero.kms.Response
	1, // 5: sidero.kms.KMSService.Unseal:output_type -> sidero.kms.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_kms_proto_init() }
func file_kms_kms_proto_init() {
	if File_kms_kms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_kms_proto_rawDesc), len(file_kms_kms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_kms_proto_goTypes,
		DependencyIndexes: file_kms_kms_proto_depIdxs,
		MessageInfos:      file_kms_kms_proto_msgTypes,
	}.Build()
	File_kms_kms_proto = out.File
	file_kms_kms_proto_goTypes = nil
	file_kms_kms_proto_depIdxs = nil
}
