// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: kms/kms.proto

package kms

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KMSService_Heartbeat_FullMethodName = "/sidero.kms.KMSService/Heartbeat"
	KMSService_Seal_FullMethodName      = "/sidero.kms.KMSService/Seal"
	KMSService_Unseal_FullMethodName    = "/sidero.kms.KMSService/Unseal"
)

// KMSServiceClient is the client API for KMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KMSService provides APIs to encrypt and decrypt data.
type KMSServiceClient interface {
	Heartbeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Seal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Unseal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type kMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKMSServiceClient(cc grpc.ClientConnInterface) KMSServiceClient {
	return &kMSServiceClient{cc}
}

func (c *kMSServiceClient) Heartbeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KMSService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Seal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KMSService_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Unseal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KMSService_Unseal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMSServiceServer is the server API for KMSService service.
// All implementations must embed UnimplementedKMSServiceServer
// for forward compatibility.
//
// KMSService provides APIs to encrypt and decrypt data.
type KMSServiceServer interface {
	Heartbeat(context.Context, *Request) (*Response, error)
	Seal(context.Context, *Request) (*Response, error)
	Unseal(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedKMSServiceServer()
}

// UnimplementedKMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKMSServiceServer struct{}

func (UnimplementedKMSServiceServer) Heartbeat(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedKMSServiceServer) Seal(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedKMSServiceServer) Unseal(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Unseal not implemented")
}
func (UnimplementedKMSServiceServer) mustEmbedUnimplementedKMSServiceServer() {}
func (UnimplementedKMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeKMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMSServiceServer will
// result in compilation errors.
type UnsafeKMSServiceServer interface {
	mustEmbedUnimplementedKMSServiceServer()
}

func RegisterKMSServiceServer(s grpc.ServiceRegistrar, srv KMSServiceServer) {
	// If the following call panics, it indicates UnimplementedKMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KMSService_ServiceDesc, srv)
}

func _KMSService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Heartbeat(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Seal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Unseal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Unseal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Unseal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Unseal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// KMSService_ServiceDesc is the grpc.ServiceDesc for KMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sidero.kms.KMSService",
	HandlerType: (*KMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _KMSService_Heartbeat_Handler,
		},
		{
			MethodName: "Seal",
			Handler:    _KMSService_Seal_Handler,
		},
		{
			MethodName: "Unseal",
			Handler:    _KMSService_Unseal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms/kms.proto",
}
